<a href="https://colab.research.google.com/github/Mehadi2012/Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.array([1,2,3,4,5], dtype=float)

array([1., 2., 3., 4., 5.])

# 2D Array

In [18]:
np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype=int)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [30]:
np.zeros(10, dtype = int) # Create an array filled with zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.ones((5,5), dtype = float) # Create a 2D array filled with ones. The first value in the parameter indicates the number rows and the other indicated the number of column.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.random.random((4,3)) # An array filled with random values between 0 and 1

array([[0.59494602, 0.30685709, 0.48929663],
       [0.98918699, 0.90861397, 0.01975347],
       [0.93851603, 0.73668059, 0.9672868 ],
       [0.09565275, 0.77065394, 0.78606724]])

In [5]:
arr = np.array([1,2,3,4,5,6], dtype = int)
print(arr)
print(arr[0])

[1 2 3 4 5 6]
1


In [70]:
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype = int)
print(arr1)
print(arr1[0,4])
print(arr1[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5
10


# 1D Slicing

In [44]:
# Slice: an_array[start:end:step]

x = np.arange(10)
print(x)
print(x[:5])
print(x[5:])
print(x[3:6])
print(x[::2])  # Here 2 indicates the step
print(x[1::2])
print(x[1::-1])
print(x[1::-2])
print(x[::-1])
print(x[::-2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[3 4 5]
[0 2 4 6 8]
[1 3 5 7 9]
[1 0]
[1]
[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]


# 2D Slicing

In [68]:
x3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype = int)
print(x3[:3, :4])
print('\n',x3[:1, :2])
print('\n',x3[1:2, 0:3])
print('\n',x3[:3, ::2])
print('\n',x3[:3, :2:2])  # Here :3 means we are taking all the rows. :2 means we are taking column from 0 to 1. :2 means we are taking every other column.
print('\n',x3[:3, ::4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 [[1 2]]

 [[5 6 7]]

 [[ 1  3]
 [ 5  7]
 [ 9 11]]

 [[1]
 [5]
 [9]]

 [[1]
 [5]
 [9]]


# reshape() Method

In [75]:
grid = np.arange(1,10).reshape((3,3)) # Here we reshaping a 1D array into 3 rows and 3 columns of 2D array.
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
grid1 = np.arange(10).reshape((2,5))
print(grid1)

[[0 1 2 3 4]
 [5 6 7 8 9]]
