<a href="https://colab.research.google.com/github/Mehadi2012/Data-Science/blob/main/Universal_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- \+ np.add -> Addition(e.g., 1 + 1 = 2)
- \- np.subtract -> Subtraction(e.g., 2 - 1 = 1)
- \- np.negative -> Unary negative(e.g., -3)
- \* np.multiply -> Multiplication(e.g., 3 * 2 = 6)
- / np.divide -> Division(e.g., 3 / 2 = 1.5)
- // np.floor_divide -> Floor Division(e.g., 3 // 2 = 1)
- \** np.power -> Exponentiation(e.g., 2 ** 2 = 4)
-  % np.mod -> Modulus/remainder(e.g., 9 % 4 = 1)

In [3]:
import numpy as np
an_array = np.arange(10)
print(an_array)
print(an_array + 2)
print(an_array - 2)
print(an_array * 2)
print(an_array / 2)
print(an_array // 2)
print(an_array ** 2)
print(an_array % 2)

[0 1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10 11]
[-2 -1  0  1  2  3  4  5  6  7]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 0 1 1 2 2 3 3 4 4]
[ 0  1  4  9 16 25 36 49 64 81]
[0 1 0 1 0 1 0 1 0 1]


# Aggregation Functions

In [17]:
an_array1 = np.array([1,2,3,4,5,6,7,8,9,10], dtype = float)
print(an_array1)
print(an_array1.max())
print(an_array1.min())
print(an_array1.sum())

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
10.0
1.0
55.0


In [15]:
my_array = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype=int)
print(my_array)
print(my_array.max(axis = 0)) # axis 0 indicates the column.
print(my_array.max(axis = 1)) # axis 1 indicates the row

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
[ 5 10]
