<a href="https://colab.research.google.com/github/Mehadi2012/Data-Science/blob/main/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Computation on Arrays

In [1]:
import numpy as np
a = np.array([0,1,2,3])
b = np.array([4,5,6,7])
c = a + b
print(c)

[ 4  6  8 10]


# Rules of Broadcasting
- 1. If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
- 2. If the shape of the two arrays does not match in any dimension, they array with shape equal to 1 in that dimension is stretched to match the other shape
- 3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised

In [2]:
x = np.arange(4)
x1 = x + 5
print(x)
print(x1)

[0 1 2 3]
[5 6 7 8]


In [4]:
y = np.ones((3,3), dtype = int)
y1 = np.arange(3)
y2 = y + y1
print(y)
print(y1)
print(y2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0 1 2]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
z = np.ones((3,1), dtype = int)
z1 = np.arange(3)
z2= z + z1
print(z) # Here we created a 2D array with 3 rows and 1 column
print(z1) # Here we created an array
print(z2) # after the addtion between z and z1 we can see that we have now an 2D array with 3 rows and 3 columns(at first it was 1). The coulumns increased because of the 1D array with 3 values.

[[1]
 [1]
 [1]]
[0 1 2]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Comparison Functions

In [10]:
my_arr = np.array([1,2,3,4,5,6,7])
print(my_arr > 0)
print(my_arr > 3)
print(my_arr >= 4)
print(my_arr <= 5)
print(my_arr == 3)
print(my_arr != 4)

[ True  True  True  True  True  True  True]
[False False False  True  True  True  True]
[False False False  True  True  True  True]
[ True  True  True  True  True False False]
[False False  True False False False False]
[ True  True  True False  True  True  True]
